<#ftl strip_whitespace="true">
<#assign importList = [] />
<#assign javaList = false />
package org.genevaers.engine.extractor;

import java.io.FileWriter;
import java.nio.ByteBuffer;

import org.genevaers.genevaio.ltfile.LTRecord;
import org.genevaers.genevaio.recordreader.RecordFileWriter;
import org.genevaers.utilities.GersCodePage;

/**
 * This class was automatically generated by the GenevaERS Component Generator.
 * 
 * DO NOT EDIT
 * 
 */
 
 public class Extract implements Extractor {
    public void processRecord(byte[] src, byte[] target, RecordFileWriter outWriter) {

<#list exrecs as rec>
${rec}
</#list>

        if(src[29] < 11) {
            byte[] stringBuffer = new byte[19];
            System.arraycopy(src, 0, stringBuffer, 0, 19);
            System.arraycopy(GersCodePage.ebcdicToAscii(stringBuffer), 0, target, 2, 19);
            target[21] = src[30];
            outWriter.getRecordToFill().bytes.position(20);
            outWriter.writeAndClearTheRecord();
        }
    }

    @Override
    public void processRecord(LTRecord lt, FileWriter outWriter) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'processRecord'");
    }
}
