<#ftl strip_whitespace="true">
<#assign importList = [] />
<#assign javaList = false />
package org.genevaers.engine.extractor;

import java.io.FileWriter;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.genevaers.genevaio.ltfile.LTRecord;
import org.genevaers.genevaio.recordreader.RecordFileWriter;
import org.genevaers.utilities.GersCodePage;

/**
 * This class was automatically generated by the GenevaERS Extract Generator.
 * 
 * DO NOT EDIT
 * 
 */
 
 public class XLT extends Extract {

    public XLT() {
<#list inputdds as ip>
        inputDDnames.add("${ip}");
</#list>
    }

    public void processRecord(byte[] src, ByteBuffer target, RecordFileWriter outWriter) {

<#list exrecs as rec>
${rec}
</#list>
    }

    public int getOutputLen() {
        return  ${outLen};
    }

    public int getLrLen() {
        return  ${lrLen};
    }


}
