package org.genevaers.engine.extractor;

import java.util.ArrayList;
import java.util.List;

/**
 * This class was automatically generated by the GenevaERS Component Generator.
 * 
 * DO NOT EDIT
 * 
 */
 
 public abstract class Extract implements Extractor {
    protected List<String> inputDDnames = new ArrayList<>();

    public Extract() {
    }

    public List<String> getInputDDnames() {
        return inputDDnames;
    }

 }
