# Test: ${test.name}
# Input
GENERATE_RC_FILES=Y
INPUT_TYPE=WBXML            # WBXML or VDPML or DB2

XLT_REPORT=Y
JLT_REPORT=Y
VDP_REPORT=Y
REPORT_FORMAT=TEXT
RCA_REPORT=Y
COMPARE=N
COVERAGE=Y

LOG_LEVEL=DEBUG # DEBUG or STANDARD
#DOT_XLT=Y